### ISSUE TITLE
Attention map visualization

### ISSUE THREAD

**Issue by gaviotas** [lsa1997/CARIS#4]
Thank you for your interesting work :) 

I am curious about the specific code for visualizing the attention map of Figure 5. What does "visual features from the second level" refer to? And could you provide information on how to normalize the attention weight?

If it's possible to obtain the code for attention map visualization, it would be greatly helpful.

**Comment by lsa1997** [comment]
Hi, I have updated the code to support attention visualization. Now, you can obtain a group of attention maps by setting return_attn=True during inference:
`pred, attn = caris_model(image, sentence, l_mask=l_mask, return_attn=True)`
Concretely, `attn` is a list of length equal to `num_levels` in the decoder, from low resolution to high resolution. The shape of each element is `[B, N_layer, N_l, H, W]`. You can change the index of the third dimension to visualize [CLS] token (index=0) or mask prompts (index ranges from -5 to -1 since we use 5 prompts) for different layers.

**Comment by gaviotas** [comment]
Thank you for getting back to me so quickly :)

I attempted to generate the attention map of [CLS] token using the updated code. However, I encountered inverted results, such as low attention weights within the ground-truth region, as shown below.

![image](https://github.com/lsa1997/CARIS/assets/26818817/e1720ca7-30a6-43cd-940a-233075a6e080)

Is this result correct, or is there an additional post-processing method I should apply to visualize the final attention map more accurately as shown in Figure 5?

**Comment by lsa1997** [comment]
In my experiments, I did notice that in some cases, the visualization results in some layers were inverted, i.e., high weights in non-target areas of [CLS] token, or high weights in target areas of mask prompts. 
The attention maps come from the cross-attention layers where visual features are query and linguistic features are key/value. They are considered to improve the discrepancy between target and non-target areas but are not directly supervised like prediction maps. Therefore, such inverted results are acceptable since they also show a clear perception of the target object and the background to facilitate final predictions. 
For better visualization, you can use `1-attn_map` as inverted maps in these cases.

**Comment by gaviotas** [comment]
I understood. Thank you for the clear explanation :)
